<script setup>
import {computed,ref} from 'vue';
const props=defineProps({columns:Array,rows:Array,sortable:{type:Boolean,default:true},defaultSort:{type:String,default:''},defaultDirection:{type:Number,default:1}});const sortKey=ref(props.defaultSort),sortDirection=ref(props.defaultDirection);
function sort(column){if(!props.sortable||column.sortable===false)return;if(sortKey.value===column.key)sortDirection.value*=-1;else{sortKey.value=column.key;sortDirection.value=column.defaultDirection??1}}
function compare(a,b,direction){if(a==null&&b==null)return 0;if(a==null)return 1;if(b==null)return-1;const na=Number(a),nb=Number(b);if(a!==''&&b!==''&&Number.isFinite(na)&&Number.isFinite(nb))return(na-nb)*direction;return String(a).localeCompare(String(b),'zh-CN',{numeric:true})*direction}
function marketPrefix(row){const market=String(row?.market||'').toLowerCase();if(['sh','sz','bj'].includes(market))return market;const code=String(row?.stock_code||'');if(code.startsWith('6'))return'sh';if(code.startsWith('8')||code.startsWith('9'))return'bj';return'sz'}
function quoteLinks(row){const symbol=`${marketPrefix(row)}${row.stock_code}`;return{eastmoney:`https://quote.eastmoney.com/concept/${symbol}.html`,sina:`https://finance.sina.com.cn/realstock/company/${symbol}/nc.shtml`}}
const displayedRows=computed(()=>{const values=[...(props.rows||[])];if(!props.sortable||!sortKey.value)return values;const column=props.columns.find(value=>value.key===sortKey.value),key=sortKey.value,direction=sortDirection.value;return values.sort((a,b)=>compare(column?.sortValue?column.sortValue(a):a[key],column?.sortValue?column.sortValue(b):b[key],direction))});
</script>
<template><div v-if="!rows?.length" class="empty">暂无数据</div><div v-else class="table-wrap"><table><thead><tr><th v-for="c in columns" :key="c.key"><button v-if="sortable&&c.sortable!==false" class="sort-button" @click="sort(c)" :aria-label="`按${c.label}排序`"><span>{{c.label}}</span><i>{{sortKey===c.key?(sortDirection===1?'▲':'▼'):'↕'}}</i></button><template v-else>{{c.label}}</template></th></tr></thead><tbody><tr v-for="(row,i) in displayedRows" :key="row.id||i"><td v-for="c in columns" :key="c.key" :class="c.class?.(row[c.key],row)"><div v-if="c.key==='stock_code'&&row.stock_code" class="stock-code-cell"><button v-if="c.action" class="table-link" @click="c.action(row)">{{c.format?c.format(row[c.key],row):row[c.key]}}</button><span v-else>{{c.format?c.format(row[c.key],row):row[c.key]}}</span><span class="quote-links"><a :href="quoteLinks(row).eastmoney" target="_blank" rel="noopener noreferrer" title="在东方财富查看行情">东财</a><a :href="quoteLinks(row).sina" target="_blank" rel="noopener noreferrer" title="在新浪财经查看行情">新浪</a></span></div><button v-else-if="c.action" class="table-link" @click="c.action(row)">{{c.format?c.format(row[c.key],row):row[c.key]??'—'}}</button><template v-else>{{c.format?c.format(row[c.key],row):row[c.key]??'—'}}</template></td></tr></tbody></table></div></template>
