<script setup>
import {onBeforeUnmount,onMounted,ref,watch} from 'vue';import {fmt,get,pct} from '../api/client';import DataTable from './DataTable.vue';
const props=defineProps({stock:{type:Object,default:null},modelCode:{type:String,default:''}}),emit=defineEmits(['close']),rows=ref([]),rankingRows=ref([]),loading=ref(false),error=ref('');
const columns=[{label:'日期',key:'trade_date'},{label:'开盘',key:'open_price',format:v=>fmt(v,2)},{label:'最高',key:'high_price',format:v=>fmt(v,2)},{label:'最低',key:'low_price',format:v=>fmt(v,2)},{label:'收盘',key:'close_price',format:v=>fmt(v,2)},{label:'涨跌幅',key:'change_pct',format:v=>v==null?'—':`${fmt(v,2)}%`},{label:'成交额(亿)',key:'amount',format:v=>v==null?'—':fmt(v/1e8,2)},{label:'换手率',key:'turnover_pct',format:v=>v==null?'—':`${fmt(v,2)}%`}];
const rankColumns=[{label:'预测基准日',key:'base_date'},{label:'完整排名',key:'full_ranking'},{label:'排名变化',key:'full_ranking_change',format:v=>v==null?'—':v>0?`↑${v}`:v<0?`↓${Math.abs(v)}`:'持平'},{label:'正式候选',key:'is_candidate',format:v=>v?'Top30':'—'},{label:'评分',key:'score',format:v=>fmt(v,3)},{label:'上涨概率',key:'up_probability',format:pct},{label:'预计收益',key:'expected_return',format:pct}];
async function load(){rows.value=[];rankingRows.value=[];error.value='';if(!props.stock)return;loading.value=true;try{const model=props.modelCode||props.stock.model_code||'';const tasks=[get(`/stocks/${props.stock.stock_code}/daily?limit=120`)];if(model)tasks.push(get(`/predictions/ranking-history?model_code=${encodeURIComponent(model)}&stock_code=${props.stock.stock_code}&limit=30`));const values=await Promise.all(tasks);rows.value=values[0].slice().reverse();const history=values[1]||[];rankingRows.value=history.map((row,index)=>({...row,full_ranking_change:history[index+1]?.full_ranking==null||row.full_ranking==null?null:history[index+1].full_ranking-row.full_ranking}))}catch(e){error.value=e.message}finally{loading.value=false}}
function onKey(event){if(event.key==='Escape'&&props.stock)emit('close')}watch([()=>props.stock,()=>props.modelCode],load,{immediate:true});onMounted(()=>window.addEventListener('keydown',onKey));onBeforeUnmount(()=>window.removeEventListener('keydown',onKey));
</script>
<template><Teleport to="body"><div v-if="stock" class="modal-backdrop" @click.self="$emit('close')"><section class="stock-modal card" role="dialog" aria-modal="true" :aria-label="`${stock.stock_code} 历史详情`"><div class="detail-heading"><div><h2>{{stock.stock_code}} · {{stock.stock_name}}</h2><span class="modal-caption">历史行情与当前模型排名轨迹</span></div><button @click="$emit('close')">关闭</button></div><div v-if="loading" class="modal-status">数据加载中…</div><div v-else-if="error" class="modal-status negative">{{error}}</div><template v-else><div v-if="modelCode||stock.model_code" class="section"><h2>模型排名历史</h2><p v-if="!rankingRows.length" class="hint">完整排名从功能上线后的新预测开始积累。</p><DataTable v-else :columns="rankColumns" :rows="rankingRows" default-sort="base_date" :default-direction="-1"/></div><div class="section"><h2>最近120个交易日行情</h2><DataTable :columns="columns" :rows="rows" default-sort="trade_date" :default-direction="-1"/></div></template></section></div></Teleport></template>
