<script setup>
import {onMounted,ref} from 'vue';import {get,fmt} from '../api/client';import DataTable from '../components/DataTable.vue';
const q=ref(''),market=ref(''),rows=ref([]),daily=ref([]),code=ref(''),page=ref(1),pages=ref(1),total=ref(0),pageSize=ref(20),upStreak=ref(0),downStreak=ref(0),minPct=ref(''),maxPct=ref('');
async function search(reset=false){if(reset)page.value=1;const params=new URLSearchParams({q:q.value,market:market.value,page:page.value,page_size:pageSize.value,min_up_streak:upStreak.value,min_down_streak:downStreak.value});if(minPct.value!=='')params.set('min_change_pct',minPct.value);if(maxPct.value!=='')params.set('max_change_pct',maxPct.value);const result=await get(`/stocks?${params}`);rows.value=result.items;pages.value=result.pages;total.value=result.total}
async function turn(target){if(target<1||target>pages.value)return;page.value=target;await search()}
async function open(c){code.value=c;daily.value=await get(`/stocks/${c}/daily?limit=120`)}
onMounted(search);
const stocks=[{label:'代码',key:'stock_code',action:r=>open(r.stock_code)},{label:'名称',key:'stock_name'},{label:'市场',key:'market'},{label:'最新日期',key:'latest_date'},{label:'最新收盘',key:'latest_close'},{label:'最新涨跌',key:'latest_change_pct',format:v=>v==null?'—':`${fmt(v)}%`},{label:'连涨',key:'up_streak',format:v=>`${v}天`},{label:'连跌',key:'down_streak',format:v=>`${v}天`}];
const prices=[{label:'日期',key:'trade_date'},{label:'开盘',key:'open_price'},{label:'收盘',key:'close_price'},{label:'最高',key:'high_price'},{label:'最低',key:'low_price'},{label:'涨跌幅',key:'change_pct',format:v=>v==null?'—':`${fmt(v)}%`},{label:'成交额(亿)',key:'amount',format:v=>fmt(v/1e8)}]
</script>
<template>
  <div class="card stock-filter"><h2>行情筛选</h2><div class="filter-grid"><label>代码或名称<input v-model="q" @keyup.enter="search(true)" placeholder="输入股票代码或名称"></label><label>市场<select v-model="market"><option value="">全部市场</option><option>SH</option><option>SZ</option><option>BJ</option></select></label><label>最少连涨天数<input v-model.number="upStreak" type="number" min="0"></label><label>最少连跌天数<input v-model.number="downStreak" type="number" min="0"></label><label>最新涨幅下限(%)<input v-model="minPct" type="number" step="0.1" placeholder="不限"></label><label>最新涨幅上限(%)<input v-model="maxPct" type="number" step="0.1" placeholder="不限"></label><label>每页数量<select v-model="pageSize"><option :value="10">10条</option><option :value="20">20条</option><option :value="50">50条</option><option :value="100">100条</option></select></label><button @click="search(true)">应用筛选</button></div></div>
  <div class="stock-grid"><section><div class="section-heading"><h2>股票列表</h2><span>共 {{total}} 条 · 点击代码查看详情</span></div><DataTable :columns="stocks" :rows="rows"/><div class="pagination"><button :disabled="page<=1" @click="turn(page-1)">上一页</button><span>第 {{page}} / {{pages}} 页</span><button :disabled="page>=pages" @click="turn(page+1)">下一页</button></div></section><section v-if="daily.length"><div class="section-heading"><h2>{{code}} 最近行情</h2><span>{{daily.length}} 条</span></div><DataTable :columns="prices" :rows="daily.slice().reverse().slice(0,30)"/></section></div>
</template>
