<script setup>
import {onMounted,onUnmounted,ref} from 'vue';import {get} from '../api/client';import DataTable from '../components/DataTable.vue';
function localDate(value=new Date()){return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`}
const today=localDate(),jobs=ref([]),selected=ref(null),dataDir=ref('data'),source=ref('sina'),top=ref(30),tradeDate=ref(today),message=ref(''),timer=ref();
const scheduleEnabled=ref(false),scheduleTime=ref('15:20'),scheduleDays=ref([1,2,3,4,5]),scheduleSource=ref('sina'),scheduleTop=ref(30),scheduleDataDir=ref('data'),scheduleInfo=ref({}),scheduleMessage=ref('');
const dayNames={1:'周一',2:'周二',3:'周三',4:'周四',5:'周五',6:'周六',7:'周日'};
function previousDate(){const value=new Date(`${tradeDate.value||today}T12:00:00`);value.setDate(value.getDate()-1);tradeDate.value=localDate(value)}
function toggleDay(day){scheduleDays.value=scheduleDays.value.includes(day)?scheduleDays.value.filter(value=>value!==day):[...scheduleDays.value,day].sort()}
const labels={collect:'拉取收盘增量',predict:'执行预测',verify:'执行正式验证',intraday:'获取盘中观察',pipeline:'完整每日流水线'};
const taskHelp={collect:{time:'当天需15:10后',text:'默认拉取当天收盘；选择以前的交易日可补拉历史行情。结果会同步数据库，已有“股票+交易日”记录会安全更新。'},predict:{time:'行情同步后',text:'使用当前最新日线计算因子和候选名单。相同基准日重复执行会更新同一批次，不重复创建行情。'},verify:{time:'下一交易日收盘行情入库后',text:'用实际次日收盘价验证已有预测。行情不足时只显示等待验证；重复执行会更新同一验证结果。'},intraday:{time:'交易时段内按需执行',text:'获取一次实时快照并新增盘中观察记录，不修改历史日线、预测候选或正式验证。'},pipeline:{time:'交易日15:10后推荐',text:'依次执行收盘增量、同步日线、验证上一期、生成下一期预测，是日常收盘后的标准流程。'}};
async function refresh(){jobs.value=await get('/tasks?limit=30');if(selected.value)selected.value=await get(`/tasks/${selected.value.id}`);const active=jobs.value.some(x=>['pending','running'].includes(x.status));if(active&&!timer.value)timer.value=setInterval(refresh,2000);if(!active&&timer.value){clearInterval(timer.value);timer.value=null}}
async function loadSchedule(){const value=await get('/tasks/schedule');scheduleInfo.value=value;scheduleEnabled.value=Boolean(value.enabled);scheduleTime.value=String(value.run_time).slice(0,5);scheduleDays.value=String(value.weekdays).split(',').map(Number);scheduleSource.value=value.data_source;scheduleTop.value=value.top_n;scheduleDataDir.value=value.data_dir}
async function saveSchedule(){scheduleMessage.value='';if(!scheduleDays.value.length){scheduleMessage.value='请至少选择一个执行日';return}try{const r=await fetch('/api/tasks/schedule',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:scheduleEnabled.value,run_time:scheduleTime.value,weekdays:scheduleDays.value,data_dir:scheduleDataDir.value,source:scheduleSource.value,top:Number(scheduleTop.value)})});const body=await r.json();if(!r.ok)throw new Error(body.detail||'保存失败');scheduleInfo.value=body;scheduleMessage.value='定时配置已保存'}catch(e){scheduleMessage.value=e.message}}
async function submit(job_type){message.value='';try{const payload={job_type,data_dir:dataDir.value,source:source.value,top:Number(top.value)};if(job_type==='collect')payload.trade_date=tradeDate.value||null;const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.detail||'提交失败');message.value=`任务 #${body.id} 已提交`;await refresh()}catch(e){message.value=e.message}}
async function show(row){if(selected.value?.id===row.id){selected.value=null;return}selected.value=await get(`/tasks/${row.id}`)}onMounted(()=>Promise.all([refresh(),loadSchedule()]));onUnmounted(()=>timer.value&&clearInterval(timer.value));
const columns=[{label:'任务ID',key:'id',format:v=>`#${v}`,action:show},{label:'任务',key:'job_type',format:v=>labels[v]||v},{label:'状态',key:'status'},{label:'进度',key:'progress',format:v=>`${v}%`},{label:'创建时间',key:'created_at'},{label:'结束时间',key:'finished_at'}];
</script>
<template>
  <div class="card schedule-panel"><div class="detail-heading"><div><h2>自动任务</h2><span class="modal-caption">后端服务运行期间，按设定时间自动执行每日完整流水线</span></div><label class="switch"><input v-model="scheduleEnabled" type="checkbox"><span>{{scheduleEnabled?'已启用':'已停用'}}</span></label></div>
    <div class="schedule-grid"><label>执行时间<input v-model="scheduleTime" type="time"></label><label>数据目录<input v-model="scheduleDataDir"></label><label>行情来源<select v-model="scheduleSource"><option value="sina">新浪</option><option value="eastmoney">东方财富</option><option value="auto">自动切换</option></select></label><label>候选数量<input v-model.number="scheduleTop" type="number" min="1" max="500"></label></div>
    <div class="weekday-row"><span>执行日</span><button v-for="(name,day) in dayNames" :class="{active:scheduleDays.includes(Number(day))}" @click="toggleDay(Number(day))">{{name}}</button></div>
    <div class="schedule-footer"><div><span>下次执行：{{scheduleInfo.next_run_at||'停用后不执行'}}</span><span>上次触发：{{scheduleInfo.last_trigger_date||'尚未执行'}}<template v-if="scheduleInfo.last_job_id"> · 任务 #{{scheduleInfo.last_job_id}}</template></span></div><button @click="saveSchedule">保存定时配置</button></div><p v-if="scheduleMessage" class="notice">{{scheduleMessage}}</p>
  </div>
  <div class="card task-panel"><h2>新建任务</h2><p class="hint">任务在后台执行，同一时间只允许一个任务运行。</p><div class="safety-note"><b>数据安全：</b>日线按“股票+交易日”唯一保存；重复同步不会生成重复行情。当天收盘增量需在15:10后拉取，历史日期可补拉。</div>
    <div class="task-config"><label>数据目录<input v-model="dataDir"></label><label>行情来源<select v-model="source"><option value="sina">新浪</option><option value="eastmoney">东方财富</option><option value="auto">自动切换</option></select></label><label>候选数量<input v-model.number="top" type="number" min="1" max="500"></label><label>收盘行情日期<div class="date-input-row"><input v-model="tradeDate" type="date" :max="today"><button type="button" @click="previousDate">前一日</button><button type="button" @click="tradeDate=today">今天</button></div><small>可点日期或快捷按钮；过去日期表示补拉。</small></label></div>
    <div class="task-actions"><article v-for="(label,key) in labels"><div><h3>{{label}}</h3><span>{{taskHelp[key].time}}</span></div><p>{{taskHelp[key].text}}</p><button @click="submit(key)">执行{{label}}</button></article></div><p v-if="message" class="notice">{{message}}</p>
  </div>
  <div class="section"><div class="section-heading"><h2>最近任务</h2><span>再次点击同一任务ID可收起</span></div><DataTable :columns="columns" :rows="jobs"/></div>
  <div v-if="selected" class="section card"><div class="detail-heading"><h2>任务 #{{selected.id}} · {{labels[selected.job_type]}}</h2><button @click="selected=null">收起详情</button></div><div class="progress"><i :style="{width:`${selected.progress}%`}"></i></div><p>状态：<b>{{selected.status}}</b>　进度：{{selected.progress}}%</p><p v-if="selected.error_message" class="negative">{{selected.error_message}}</p><pre>{{selected.log_text||'等待日志…'}}</pre></div>
</template>
